---
- name: Install Docker
  hosts: localhost
  connection: local
  become: true
  gather_facts: true  
  tasks:
#    - debug:
#        msg: "I am connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribution_version }}"
#    - name: Add {{ USER }} to admin group
    - name: install docker.io
      apt: name=docker state=latest
    - name: install docker-compose
      apt: name=docker state=latest
    - name: start docker service
      systemd: name:docker state=restarted enabled=yes 

#test $ docker run hello-world
