---
- name: Install Docker
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  vars_files:
   - vars/default.yml  
  tasks:
#    - debug:
#        msg: "I am connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribution_version }}"
#    - name: Add {{ USER }} to admin group
    - name: install docker
      apt: name=docker state=latest
    - name: install docker.io
      apt: name=docker state=latest
