---
- name: Starting task
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  tasks:
    - debug:
        msg: "I am connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribution_version }}"



# Setup metasploit database
apt-get install -y metasploit-framework
systemctl enable postgresql
service postgresql start
msfdb init
