---
- name: Create inputrc for reverse searching
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  tasks:
#    - debug:
#        msg: "I am connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribution_version }}"
    - name: Create .inputrc for {{ user }}
      ansible.builtin.file:
         path: /home/{{ user }}/.inputrc
         state: touch
    - name: Ansible Insert multiple lines using blockinfile
      blockinfile:
        dest: /home/{{ user }}/.inputrc
        block: |
          "\e[A": history-search-backward
          "\e[B": history-search-forward
          "\e[C": forward-char
          "\e[D": backward-char
        backup: yes
