---
- hosts: localhost
  connection: local
  become: true
  gather_facts: true
  vars_prompt:
    - name: User_inputrc
      prompt: "User account for inputrc?"
      private: no


  tasks:
    - name: Create .inputrc for {{ User_inputrc }}
      ansible.builtin.file:
         path: /home/{{ User_inputrc }}/.inputrc
         state: touch
    - name: Ansible Insert multiple lines using blockinfile
      blockinfile:
        dest: /home/{{ User_inputrc }}/.inputrc
        block: |
          "\e[A": history-search-backward
          "\e[B": history-search-forward
          "\e[C": forward-char
          "\e[D": backward-char
        backup: yes
