---
- name: Apt installs
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  tasks:
#    - debug:
#        msg: "I am connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribution_version }}"
    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Install a list of packages
      apt:
        pkg:
        - apt-transport-https
        - chromium
        - cifs-utils 
       # - creddump
       # - code        #requires repo and key be installed first
#docker        - ca-certificates
        - curl
        - dnsutils  
        - ecryptfs-utils
        - exif 
        - exiv2 
        - exfat-fuse 
        - exfat-utils
        - fail2ban
      #  - flashplugin-nonfree
       # - feroxbuster
        - gimp
        - git-all
        - grc
#docker        - gnupg-agent
        #- impacket-scripts
       # - icedtea-plugin
        - iperf3
        - html2text
        - htop
        - iptables
        - iptables-persistent
        - libreoffice-calc
        - libreoffice-gnome 
        - libreoffice-writer 
        - metagoofil 
        - nbtscan
        - netcat-openbsd 
        - net-tools
        - netfilter-persistent
        - nikto
        - nmap
        - onesixtyone
        - openvpn
       # - oscanner 
        - passing-the-hash
       # - powershell
        - redis-tools
        - rsync
        - sshfs
       # - sipvicious
        - smbclient 
        - smbmap 
        - snmp 
#docker        - software-properties-common
        - sshpass
      #  - sslscan
        - sudo
        - tmux
        - tmuxp
      #  - tnscmd10g
        - ufw
        - vim
        - vnstat
        - whatweb
        - wkhtmltopdf
        - wireshark
        - vncsnapshot
        - xdotool
        - xfce4-screenshooter
        
        

        


