---
- name: Ubuntu user
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  tasks:
    - debug:
        msg: "I am connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribution_version }}"
    - name: add user to sudoers.d
      lineinfile:
        path: '/etc/sudoers.d/{{ ubuntu_user }}'
        state: present
        create: yes
        regexp: '{{ ubuntu_user }} .*'
        line: '{{ ubuntu_user }} ALL=(ALL) NOPASSWD:ALL'
    
    #-e ubuntu_user 
