---
- name: Ubuntu user
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  tasks:
    - debug:
        msg: "I am connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribution_version }}"
    - name: Adding {{ USER }} to /etc/sudoers
      lineinfile:
        path: '/etc/sudoers'
        state: present
        create: yes
        regexp: '{{ USER }} .*'
        line: '{{ USER }} ALL=(ALL) NOPASSWD:ALL #managed by ansible'
    
    #-e ubuntu_user 
#3:34
