---
- name: Apt installs
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  tasks:
#    - debug:
#        msg: "I am connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribution_version }}"
    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Install a list of packages
      apt:
        pkg:
        - chromium
       # - code
        - fail2ban
        - flashplugin-nonfree
       # - feroxbuster
        - gimp
        - git
        - grc
        #- impacket-scripts
        - icedtea-plugin
        - iperf3
        - html2text
        - htop
        - libreoffice-calc
        - libreoffice-gnome 
        - libreoffice-writer 
        - nbtscan
        - netcat-openbsd 
        - nikto
        - nmap
        - onesixtyone 
       # - oscanner 
       # - powershell
        - redis-tools
        - rsync
       # - sipvicious
        - smbclient 
        - smbmap 
        - snmp 
        - sshpass
      #  - sslscan
        - tmux
        - tmuxp
      #  - tnscmd10g
        - ufw
        - whatweb
        - wkhtmltopdf
        - wireshark
        - xfce4-screenshooter

        


