---
- name: Starting task
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  tasks:
    - debug:
        msg: "I am connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribution_version }}"



#mkdir -p /usr/share/wordlists
#cd /usr/share/wordlists
#wget "http://www.phenoelit.org/dpl/dpl.html" -O /usr/share/wordlists/dpl.html
